In [ ]:
# Numpy basics

In [ ]:
import numpy as np

# They all have to be a same datatype in these lists, they are ndarray type, n dimensional array
np1 = np.array([1, 2, 3, 4])
print(np1)

np1.shape # Get the shape of the array

np2 = np.arange(10) # Create array in a range
print(np2)

np3 = np.zeros(1) # Creates an array of 0. items (not integer)
print(np3)

# Multi-dim

np4 = np.zeros((2, 3))
print(np4)

np5 = np.full((2, 10), 1)
print(np5)

# Converting lists to numpy lists
my_list = [1, 2, 3]
np6 = np.array(my_list)
print(np6)

[1 2 3 4]
[0 1 2 3 4 5 6 7 8 9]
[0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]
[1 2 3]


In [ ]:
import numpy as np

np1 = np.array([1, -2, 3, 4, 5, 6, 7, 8])
print(np1[0:5]) # Array 1 to 4, ignores 5

# Universal functions - like sqrt, abs, exp, min, max, sign (finds the sign)

print(np.sqrt(np1))
print(np.sign(np1))

[ 1 -2  3  4  5]
[1.                nan 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712]
[ 1 -1  1  1  1  1  1  1]


<ipython-input-24-b14705404843>:8: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(np1))


In [ ]:
import numpy as np

# View makes a copy that makes an exact copy (all items point to the same inner items)

np1 = np.array([1, 2, 3, 4, 5])
np_view = np1.view()

np1[0] = 10
print(np_view)

# Create a copy, does not change, like a snapshot

np_copy = np1.copy()
np1[0] = 1

print(np_copy)

[10  2  3  4  5]
[10  2  3  4  5]


In [ ]:
import numpy as np

# Shape prints rows, columns

np1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(np1.shape)

np2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(np2.shape)

# Reshaping

np3 = np1.reshape(2, 5) # Make our 10 item 1D array into a 2D 2x5 array
print(np3)

np4 = np1.reshape(1, 1, 10)
print(np4)

# Flatten

np5 = np4.reshape(-1)
print(np5)

(10,)
(2, 4)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[[ 1  2  3  4  5  6  7  8  9 10]]]
[ 1  2  3  4  5  6  7  8  9 10]
