In [ ]:
# PyTorch is the most popular current framework and utilizes the GPU
# A tensor is a numerical encoding of data / representation output of the neural network

import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


In [ ]:
# Tensors, representing multidimensional numeric data

# Scalar
scalar = torch.tensor(7)
scalar

# Dimensions
scalar.ndim # 0, no dimensions
scalar.item # Get back the item 7

# Vector, literally just a lin alg vector
vector = torch.tensor([7, 7])
vector.ndim # 1 dimension, number of pair of closing square brackets
vector.shape # 2, same as numpy

# Matrix
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

# Tensor, 3 square brackets
TENSOR = torch.tensor([[[1, 3, 4], [4, 5, 6], [7, 8, 9]]])
TENSOR.shape # 1 x 3 x 3, just a square in R3

torch.Size([1, 3, 3])

In [ ]:
# Random tensors
# The way neural networks learn is by adjusting the numbers in tensors to better represent the data
random_tensor = torch.rand(3, 4)
random_tensor

# Similar to an image tensor
image_size_tensor = torch.rand(size=(3, 224, 224)) # colour channels, height, width
image_size_tensor.ndim

3

In [ ]:
# Zeros and Ones tensors

zeroes = torch.zeros(size=(3, 4))
ones = torch.ones(size=(3, 4))
print(zeroes)
print(ones)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [ ]:
# Creating a range of tensors, use arange not range
one_to_ten = torch.arange(1, 11)

# Creating a "like" tensor
ten_zeroes = torch.zeros_like(input=one_to_ten)
print(ten_zeroes)

# Datatypes, you can check using dtype, the default is float32
# parameters that are also used are device and requires_grad
float_tensor = torch.tensor([3.0, 6.0], dtype=torch.float64)
print(float_tensor.dtype)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
torch.float64


In [ ]:
# Tensor Operations

tensor = torch.tensor([1, 2, 3])
print(tensor + 10)
print(tensor * 10)

# Matrix multiplication, use matmul() or mm(), ensure shape is okay
# matrix1 num columns = matrix 2 num rows
# Ensure the inner dimensions match as well
print(torch.matmul(tensor, tensor))

tensor_A = torch.tensor([[1, 2], [3, 4], [5, 6]])
tensor_B = torch.tensor([[7, 10], [8, 11], [9, 12]])

# torch.mm(tensor_A, tensor_B) # 3x3 and 3x2 cannot be multiplied
# To fix this issue, take the transpose of a matrix, which flips the rows and columns

print(tensor_B.T) # .T does the transpose



tensor([11, 12, 13])
tensor([10, 20, 30])
tensor(14)
tensor([[ 7,  8,  9],
        [10, 11, 12]])


In [ ]:
# Aggregate functions like min, max, sum

x = torch.arange(0, 100, 10)
print(x.max())
print((x.type(torch.float32)).mean()) # Mean does not work on Long data

# Argmax and Argmin, position of maxes and mins

print(x.argmin())
print(x.argmax())

tensor(90)
tensor(45.)
tensor(0)
tensor(9)


In [ ]:
# Stacking means we combine multiple tensors on top of each other or side-by-side, v/h stacks
# Squeeze removes all 1 dimensions in a tensor
# Unsqueeze adds a single dimension to a target tensor at a specific dimension
# Permute returns a permutation of the tensor as a view

import torch

x = torch.arange(1., 10.)

# Add an extra dimension
x_reshaped = x.reshape(3, 3)
print(x)
print(x_reshaped)

# Stacking

x_stacked = torch.stack([x, x, x]) # dim = 0
print(x_stacked)

# Squeeze

x = torch.tensor([[1, 2, 3]])
print(x.shape)
x_squeezed = x.squeeze()
print(x_squeezed.shape)

# Unsqueeze

x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(x_unsqueezed) # At 0th dimension

# Permute, returns a view, with dimensions permuted
# Used mostly with images

x_original = torch.rand(size=(244, 244, 3))
x_permuted = x_original.permute(2, 0, 1) # Puts index 2 to the front, colour channel first
print(x_permuted.shape)

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])
torch.Size([1, 3])
torch.Size([3])
tensor([[1, 2, 3]])
torch.Size([3, 244, 244])


In [ ]:
# Reproducibility, trying to take the random out of random
# We just set a seed
import torch

rand_A = torch.rand(3, 4)
rand_B = torch.rand(3, 4)

print(rand_A)
print(rand_B)

tensor([[0.6124, 0.6069, 0.6000, 0.9212],
        [0.3275, 0.1157, 0.3193, 0.0451],
        [0.3271, 0.3325, 0.2436, 0.5777]])
tensor([[0.1258, 0.9163, 0.6318, 0.2888],
        [0.7807, 0.5312, 0.8048, 0.7585],
        [0.9591, 0.4767, 0.6500, 0.6347]])


In [ ]:
# Set a seed
import torch

RANDOM_SEED = 22
torch.manual_seed(RANDOM_SEED) # Works for 1 block of code in a notebook,
# so use it twice in my case

rand_C = torch.rand(3, 4)
rand_D = torch.rand(3, 4)

print(rand_C)
print(rand_D)

tensor([[0.3659, 0.7025, 0.3104, 0.0097],
        [0.6577, 0.1947, 0.9506, 0.6887],
        [0.8174, 0.7575, 0.7492, 0.6874]])
tensor([[0.2564, 0.0672, 0.9066, 0.9175],
        [0.4236, 0.7978, 0.8594, 0.3660],
        [0.6949, 0.3343, 0.6681, 0.4951]])


In [ ]:
# To use the GPU we change the device type on the tensor
# NumPy only works with the CPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

cuda
